name: pyinstaller

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - uses: engineerd/configurator@v0.0.8
      with:
        name: "upx.exe"
        url: "https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-win64.zip"
        pathInArchive: "upx-4.0.2-win64/upx.exe"

    - run: pip install -r requirements.txt
    - run: pip install pywin32 git+https://github.com/oldnapalm/pyinstaller.git
    - run: pyinstaller bot.spec
    - run: pyinstaller cadence.spec
    - run: pyinstaller heartrate.spec
    - run: pyinstaller row.spec
    - run: pyinstaller vpower.spec

    - uses: vimtor/action-zip@v1
      with:
        files: dist cadence.csv curve.csv vpower.cfg zones.csv
        dest: vpower-nightly.zip

    - uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
      with:
        upload_url: https://uploads.github.com/repos/oldnapalm/vpower/releases/102067219/assets{?name,label}
        release_id: 102067219
        asset_path: vpower-nightly.zip
        asset_name: vpower-nightly.zip
        asset_content_type: application/zip
